# Generated by Django 4.2 on 2023-05-05 02:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_superuser_remove_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='type name')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update time')),
            ],
            options={
                'verbose_name': 'good type',
                'verbose_name_plural': 'good type',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=100, verbose_name='order_num')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('number', models.IntegerField(default=0, verbose_name='number')),
                ('image', models.FileField(upload_to='good_image', verbose_name='图片')),
                ('total_price', models.IntegerField(default=0, verbose_name='total_price')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('inventory', models.IntegerField(default=0, verbose_name='inventory')),
                ('price', models.IntegerField(default=0, verbose_name='inventory')),
                ('image', models.FileField(upload_to='good_image', verbose_name='图片')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update time')),
                ('good_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_type', to='goods.goodtype', verbose_name='good type')),
            ],
            options={
                'verbose_name': 'good',
                'verbose_name_plural': 'good',
            },
        ),
    ]
