# Generated by Django 4.2 on 2023-04-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
